### PR TITLE
Remove bogus META6.json version value check.

### PR DESCRIPTION
**Pull request by jdv**

### CODE REVIEW

**Comment by ranguard** [comment]
+1

**Comment by FROGGS** [comment]
+1

**Comment by andk** [comment]
Thanks, I've merged, pushed and deployed to pause.

The test mldistwatch-misc.t fails for me before and after the commit.

**Comment by andk** [comment]
> The test mldistwatch-misc.t fails for me before and after the commit.

Now fixed with acbba53.

**Pull request merged**
