### PR TITLE
Expand operating model list of prohibitions

### PR DESCRIPTION
**Pull request by xdg**
Expand and standardize terminology.  Additions are:
* security
* a catch all for anything else damaging to the ecosystem

### CODE REVIEW

**Comment by andk** [comment]
Thanks, David, highly appreciated! I've applied, version bumped, and deployed in the last few minutes.

**Comment by andk** [comment]
after having slept over it I think it wasn't a good idea to accept
this PR. Blame the weather, blame my ignorance, I don't know. I wasn't
in the best shape and decided quickly instead of thoroughly.

I think we really should kill the catch all part of the pull request.
The Operating Model at its very heart had the idea that we guarantee
our users that we do not interfere with their uploads unless in
narrowly defined special cases.

Now we had an incident that showed us we had forgotten to talk about
security matters. We should react to this incident with a new version
that introduces security matters. No more, no less. When we have
another case that shows us that we missed something, we should seek
how to codify additional rules. That's what the spirit of the
Operating Model kind of promises.

I've now reverted the last two commits and would ask for a second
attempt at a rephrasing, this time strictly limited to what the
security incident taught us.

Thanks && sorry for my lapse

**Comment by xdg** [comment]
With all due respect, no.

I asked for feedback 11 days ago and you had none.  I opened a PR and you accepted it without comment.  If you would like different wording, please come up with it yourself.

**Comment by andk** [comment]
Absolutely understandable. Will do. Thanks for the first version anyway.

**Comment by andk** [comment]
My version is in the branch https://github.com/andk/pause/tree/operating-model-add-security ; I'd deploy it in the near future if nobody raises doubts. Thanks for your thoughts and your patience

**Pull request merged**
